language: node_js
node_js:
  - 8
  - 6
  - 4

before_script:
- npm install -g gulp-cli
- npm install coveralls

script:
- npm run test-with-coverage

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
