language: node_js
node_js:
  - 8
  - 6
  - 4

before_script:
- npm install -g gulp-cli

script:
- npm run test-with-coverage

after_success: ./node_modules/coveralls/bin/coveralls --file=./coverage/lcov.info
